import type { Catalog } from '../messages'

export const en = {
  "skip": "Skip to main content",
  "prototype": "Directory prototype",
  "language": "Language",
  "hero.eyebrow": "Your values. Your community.",
  "hero.title": "Professional directory",
  "hero.description": "Discover vegan and vegan-friendly professionals. Explore practices and perspectives that connect with your values.",
  "hero.action": "Explore professionals",
  "sample.title": "Sample directory.",
  "sample.disclosure": "All people, categories, affiliations, and verification statuses are fictional and illustrative. Portraits are illustrations and do not identify real professionals.",
  "directory.heading": "Find your next connection",
  "results.heading": "Directory professionals",
  "results.label": "Professionals",
  "filters.label": "Filter professionals",
  "filters.category": "Professional category",
  "filters.affiliation": "Vegan affiliation",
  "filters.allCategories": "All categories",
  "filters.allAffiliations": "All affiliations",
  "filters.clear": "Clear filters",
  "feedback.clear": "Clear these filters",
  "feedback.retry": "Retry",
  "status.pending": "Loading professionals…",
  "status.populated": "Professionals ready.",
  "status.empty": "The directory is empty.",
  "status.noMatches": "No professionals match these filters.",
  "status.error": "We could not load professionals.",
  "feedback.pending": "Finding the current selection.",
  "feedback.empty": "There are no professionals to display right now. Please check again later.",
  "feedback.noMatches": "Try a different category or affiliation, or start again with all professionals.",
  "feedback.error": "Please try again. Your filter selections have been kept.",
  "name.unavailable": "Name unavailable",
  "category.unavailable": "Category unavailable",
  "affiliation.vegan": "Vegan",
  "affiliation.veganFriendly": "Vegan-friendly",
  "affiliation.unavailable": "Affiliation unavailable",
  "verification.verified": "Verified",
  "verification.notVerified": "Not verified",
  "verification.unavailable": "Verification status unavailable",
  "category.nutrition": "Nutrition",
  "category.fitness": "Fitness",
  "category.wellbeing": "Wellbeing",
  "location.remote": "Remote",
  "location.bristol": "Bristol · United Kingdom",
  "location.portland": "Portland · United States",
  "footer.context": "A prototype for building community, together.",
  "footer.disclosure": "Fictional people and sample data. Illustrative portraits.",
  "metadata.title": "Professional directory · VeganPro",
  "metadata.description": "Explore VeganPro’s sample directory of vegan and vegan-friendly professionals. Fictional people and sample data."
} satisfies Catalog
