import type { Catalog } from '../messages'

export const es = {
  "skip": "Ir al contenido principal",
  "prototype": "Prototipo de directorio",
  "language": "Idioma",
  "hero.eyebrow": "Tus valores. Tu comunidad.",
  "hero.title": "Directorio profesional",
  "hero.description": "Descubre profesionales veganos o afines al veganismo. Explora prácticas y perspectivas que conectan con tus valores.",
  "hero.action": "Explorar profesionales",
  "sample.title": "Directorio de muestra.",
  "sample.disclosure": "Todas las personas, categorías, afinidades y estados de verificación son ficticios e ilustrativos. Los retratos son ilustraciones y no identifican a profesionales reales.",
  "directory.heading": "Encuentra tu próxima conexión",
  "results.heading": "Profesionales del directorio",
  "results.label": "Profesionales",
  "filters.label": "Filtrar profesionales",
  "filters.category": "Categoría profesional",
  "filters.affiliation": "Afinidad con el veganismo",
  "filters.allCategories": "Todas las categorías",
  "filters.allAffiliations": "Todas las afinidades",
  "filters.clear": "Limpiar filtros",
  "feedback.clear": "Limpiar estos filtros",
  "feedback.retry": "Reintentar",
  "status.pending": "Cargando profesionales…",
  "status.populated": "Profesionales disponibles.",
  "status.empty": "El directorio está vacío.",
  "status.noMatches": "No hay profesionales que coincidan con estos filtros.",
  "status.error": "No pudimos cargar los profesionales.",
  "feedback.pending": "Buscando la selección actual.",
  "feedback.empty": "No hay profesionales para mostrar en este momento. Vuelve a consultar más tarde.",
  "feedback.noMatches": "Prueba otra categoría o afinidad, o vuelve a explorar todos los profesionales.",
  "feedback.error": "Inténtalo de nuevo. Conservamos tus filtros.",
  "name.unavailable": "Nombre no disponible",
  "category.unavailable": "Categoría no disponible",
  "affiliation.vegan": "Vegano",
  "affiliation.veganFriendly": "Afín al veganismo",
  "affiliation.unavailable": "Afinidad no disponible",
  "verification.verified": "Verificado",
  "verification.notVerified": "No verificado",
  "verification.unavailable": "Estado de verificación no disponible",
  "category.nutrition": "Nutrición",
  "category.fitness": "Actividad física",
  "category.wellbeing": "Bienestar",
  "location.remote": "A distancia",
  "location.bristol": "Bristol · Reino Unido",
  "location.portland": "Portland · Estados Unidos",
  "footer.context": "Un prototipo para crear comunidad, juntos.",
  "footer.disclosure": "Personas y datos ficticios. Retratos ilustrativos.",
  "metadata.title": "Directorio profesional · VeganPro",
  "metadata.description": "Explora el directorio de muestra de VeganPro con profesionales veganos y afines al veganismo. Personas y datos ficticios."
} satisfies Catalog
